### ISSUE TITLE
Load fails when component value contains 'Ω' character

### ISSUE THREAD

**Issue by calumchisholm** [Engidea/FreeRoutingNew#8]
An error is thrown when trying to load a .dsn file which contains the 'Ω' character (Unicode U+03A9) as part of a component value e.g.

`(place R8 118110 -86360 front 180 (PN 100kΩ))`

Stack trace:

`User Message=ImportDesign
Exception Class=class java.util.concurrent.ExecutionException
--> toString=java.util.concurrent.ExecutionException: java.lang.Error: Illegal character <Ω>
--> Stack=java.util.concurrent.FutureTask.report(FutureTask.java:122)
java.util.concurrent.FutureTask.get(FutureTask.java:192)
javax.swing.SwingWorker.get(SwingWorker.java:602)
freert.main.MainApplication$ImportDesign.done(MainApplication.java:265)
javax.swing.SwingWorker$5.run(SwingWorker.java:737)
javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
javax.swing.Timer.fireActionPerformed(Timer.java:313)
javax.swing.Timer$DoPostEvent.run(Timer.java:245)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by Engidea** [comment]
Can you share the dsn ? or at least the part that has the particular component name ?
(it basically saves me the time to "create" a dsn that shows the error)
Also, are you on Linux, Windoze, Mac ? Java version ?

**Comment by calumchisholm** [comment]
Sure thing -
[PromBlower_4bit.zip](https://github.com/Engidea/FreeRoutingNew/files/990376/PromBlower_4bit.zip)

```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)`
```

It was created using Kicad 4.0.6 on Fedora 25.
```
$ uname -a
Linux frink 4.10.13-200.fc25.x86_64 #1 SMP Thu Apr 27 20:39:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Engidea** [comment]
Ok, added the omega char to the accepted chars and as far as I can see it opens your board
I am wondering if you tried to autoroute it, it is in a pretty bad state regarding routing
It really need a groundplane and then you can route it pretty quickly
Anyway, please test the current release

**Comment by calumchisholm** [comment]
Thank you for that - the file loads fine for me now. The board is still something of a work in progress, so it's not really ready for routing yet, but agree that a ground plane would certainly simplify things.

**Comment by Engidea** [comment]
ok, closing this issue.
